### ISSUE TITLE
Pypi Missing Source or Wheel Files

### ISSUE THREAD

**Issue by DaAwesomeP** [ben-cohen/editrcs#2]
Hello!

Currently `pip install editrcs` is broken because no source or wheel files associated with the current release (`0.5.1`) were uploaded. This can be seen by how this page is empty: https://pypi.org/simple/editrcs/ (this is the page that `pip` uses to list downloads).

Since there are now new changes, at your convenience may a new version be released and files uploaded (probably with [`twine`](https://twine.readthedocs.io/en/stable/))?

Thanks!

**Comment by ben-cohen** [comment]
Hi, I uploaded a new version to pypi and there are now some files to download.  Could you let me know if they work for you, because I haven't done this before.

**Comment by DaAwesomeP** [comment]
I am defintely able to use `pip install editrcs` now, but I'm having some trouble importing the package. I was using `from editrcs import ParseRcs`, but now this doesn't work. I also tried `from editrcs.editrcs import ParseRcs`.

**Comment by ben-cohen** [comment]
Ahhh, thanks - I messed up `__init__.py`.  I moved `editrcs.py` back to `__init__.py` for 0.5.3 which should fix it.

**Comment by DaAwesomeP** [comment]
Perfect! Thank you so much! Really, this library has saved me so much time.

**Comment by ben-cohen** [comment]
That's great to hear, thank you!
